# 支付宝沙箱配置文件

# 应用私钥
ALIPAY_PRIVATE_KEY=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCaPQDOX/OdjYFHJrcGYWg5LSrauUoQlPZZC2aZf79reH+GJ8xKJjSrSob/PPVB1ZmR3AY8qkSLjK37gcWunqLfvc9k+KQ8NML9XOgtqSy1rs0ewMjw+cLans5FyccVLUGzRtIJZyIY+lTwZr68fhnXYgWwwUjt1pD/NABU1by2owmJB3PYzcMjJLd2Bt5najscBzMTUK6IoM4v1bpE5ow9JlrmugpLKQHvfwUy4O1XxlaxJNhWicdpCIKa5KO7m7w6PFLkz2LFuGsoZ/Fu7XCTt3C4hidyrjo8UZzJhMNHRnmLuyuHzLPpvKUx/++AO4MSEATQMhHO8FQtcpG16PYdAgMBAAECggEAJRJUh0X4v/2q/PcJNrdi3ZtFmZy/eIzVSUG8P1i9IY+s1wnpyEi2kBUxrVdxe4ljh/NibGJgZ0pA5xqh8P6gFzcACjzY/L+RvmP+SjtHS8Pf+WxM396oPvO8kHmXKDfger6i7S+kumwwzjdj0NpeS657v6g1ZzUTVMOi8MEOwra8O2wifRtt8RHjH3g5Utf0LFlDEkS+rnM8VTWMO0GnU2xM3OjMs7T8IJLmF8vD0hNu6S5T7XXsK0XkjEIFd0mr7NICaDMXCg10TeB/wSpBaQtrp04TKC4BrMpRA+MAZw7DXiM4RQhsXOlR2i+KIfN9H/secj7TdOteKA1XqJvZ4QKBgQDsBivlBxtaZAaUGdRfkXHkwGhOtCImuiE3MPEmEflARvKCEmLOvx+MjWxM8aDJC3tzGmgNMwv1DfOgX8rh579csfwxlmt+kHxKuW3xqAjpbyUg21+Li9SCqXLTEuqzbbTQGlL4wDfA1uxuTrDjkfLiidobhzOw+TbqqUrTjhRYTwKBgQCnStCrqY5Ya+knXlplsWo/JS+bxBOaFjxTo/tO40MQl59dbOL5CTbWJ3O7l2ujW6V+XKpg2shsiNA9E5lnchp33p07yx2QyNvxLw+ewi3x1Ox3WB386+by0LFRengwMLFYn7cku96D9Cra6QG/U90/39Y+4MQJ7H78P3NJTiDD0wKBgHu8iIqbfTWYNvKxz+sCX0ljrcuFGFphPkSm/eXNinSuPTj/1pk5DZssEVkNXBPKVz/y2hYBawVf+Rdc4Qop6uL31JVSnKxPpzmtmPwV8gYfZMGjAKYx+ok9uJr70dubai2nf1Q1wYTxqCX0TzwfKcymJJhF+02OecHwWvAqDnR1AoGARyzaiR6TlGUdBoXrOfb4uDLvBXuvx1AMjJ1o75BbWTTZNdt82e2kqgqQ/9AVmKQGTjPIvXp36U1wI3wyOUPfpP5OsUDirFX41a1rHOWKvKgVj1UrNQ986/QEbSEI/5/H5GfXeMaBjmyUyxx1hNx+do2aTpg8b+hxwoqQVzDpWccCgYB2J9kmfSRaGe0HajwQJY/ZtvuEwnc/zghxqWSdsrMmR3xC703J+vIq7aMx9x+smY/pN7eLMmx0SEHYMW1E8xQF4WgMsp5LmCV/9o5Z7m2rSq+lS86LcQ7U8N4oINAa7ZcaU0qPlRy1UkSkxRoczFDwNOLftNuHIKQJhcRo0SMsUQ==

# 支付宝公钥
ALIPAY_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3i7AnUJSku7M/vYG+FnKZCKdV1KwZsHt1NN0sA0S5qyeDJpOUcEPFe2VSB/aMqhkNNLzDe+yibpRlucrBZMW3T/IY21a8/pbl/c0rIBScl7Z+wJVYruFxovNDNKme7Za7he/mBRs9iUyS5KulOsmz3BokqBDvMZ3a0RNjFeRX1vzG7wJKxU7ivwC7Pigvkwg8mCNVzHhi8ry7UmKM4NayUIzu1s3A1mqMf3sqhk4k+tt3A3bW3Qcuv+EjEgHbRcKm5/1F3O1/hsql6e5ePG8847zF0Q0wic6FEHTT0mUPZq01PqH+g5nccP+Mv4ceJjfDp5mpc21oV1CLJUbaii2SwIDAQAB

# 应用ID
ALIPAY_APP_ID=202100617693097

# 沙箱网关
ALIPAY_GATEWAY_URL=https://openapi-sandbox.dl.alipaydev.com

# 回调地址
ALIPAY_NOTIFY_URL=http://8.137.58.214:8082/api/payments/alipay/notify

# 返回地址
ALIPAY_RETURN_URL=http://localhost:3000/pay/result
